### ISSUE TITLE
请问，实例9中报错找不到fs.promised模块，需要做啥呢？

### ISSUE THREAD

**Issue by dadiu** [ruanyf/koa-demos#6]
代码
```js
const Koa = require('koa');
const fs = require('fs.promised');
const app = new Koa();

const main = async function (ctx, next){

    ctx.response.type = 'html';
    ctx.response.body = await fs.readFile('./demos/template.html', 'utf8');

}

app.use(main);
app.listen(3000);


```

报错
```js
Error: Cannot find module 'fs.promised'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (f:\github\myStudy\koa\demos\10.js:2:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by ruanyf** [comment]
npm install
